### PR TITLE
Add timeout parameter to NetworkPrintConnector

### LINKED ISSUE #348: Add timeout to NetworkPrintConnector
In my experience, connecting to printers via the `NetworkPrintConnector` either succeeds quickly or times out. It would be nice to add a configurable timeout parameter to the `NetworkPrintConnector` constructor. [`fsockopen()`](http://php.net/manual/en/function.fsockopen.php) already supports this, so it should be as simple as adding a pass-through parameter.

**Question**: I need to find out what the default timeout is for `fsockopen`. That should be the new parameter's default value in the constructor. This way existing implementations will not be affected in any way.

I should have some time in the next few days to add this and submit a PR but I thought I'd open an issue for discussion.

### PR DESCRIPTION
**Pull request by Stenerson**
Default to ini_get(‘default_socket_timeout’) or 60 seconds
Closes #348

### CODE REVIEW

**Comment by Stenerson** [comment]
I have a few notes/questions on this:
- This is a really simple change but since [`fsockopen`](http://php.net/manual/en/function.fsockopen.php) uses `ini_get("default_socket_timeout")` as its default value I needed to take the "default" value out of the function declaration.
- 99.99999% of installations should have the `default_socket_timeout` defined but I think it is possible that someone doesn't have it in their ini. So, for backwards compatibility I defaulted to 60 seconds if that ini value isn't defined.
- Are you ok with the ternary operators? Specifically Elvis operators? 
- Is there any way to include tests for this? I tested a bunch of different scenarios but didn't know how/if it was possible to add automated tests.
- I didn't change any doc (other than the doc block) because I figured this is an advanced feature and would only add confusion to beginners. I'm happy to add doc or examples if you think it would help

**Comment by mike42** [comment]
Thanks for submitting. I'll give this a test over the weekend before I merge it, but I agree that is a useful change.

In particular, if your socket timeout exceeds your PHP execution limit, I can see how you would get problems.

It is possible to avoid `ini_get()` if it causes trouble, which would look something like-

```php
function foo($bar, $baz = null) {
    if($baz === null) {
        // let PHP do the default
        $quux = @warble($bar);
    } else {
        // Use the user-provided one
        $quux = @warble($bar, $baz);
    }
    if($quux === false) {
        // error handling
    }
}
```

**Comment by Stenerson** [comment]
Hmm, I could go either way. I'll let you decide which style you prefer. I can easily update the PR and run a few more local tests if you want me to change it.

I do think it's **highly** unlikely that someone's ini wouldn't have that key. Using 60 seconds as the default seems reasonable since it's been the [default since php 4.3.0](http://php.net/manual/en/filesystem.configuration.php) which was released in Dec, 2002.

**Comment by Stenerson** [comment]
@mike42 any update on this? I'm currently using a forked version in production but would like to get back to the project master if possible. Thanks!

**Comment by mike42** [comment]
Merged. I'll sort out a point release.

Thanks for sending this through!

**Pull request merged**
