### PR TITLE
Namespace

### PR DESCRIPTION
**Pull request by brndwgn**
# The Good
I've restructured and namespaced all the classes and added use statements where appropriate to allow composer autoloading to work. 

I've also added the print buffer cache folder to the .gitignore.

# The Bad
I haven't tested the ImageMagick related things since I didn't need them for my project.

# The Unrelated
I've used this package successfully with a Tysso PRP-300 Thermal Receipt Printer, so you can add that to the list of supported printers if you like.

### CODE REVIEW

**Comment by mike42** [comment]
Hi brndwgn,

Legenndary work- these are all good changes. This will most likely be accepted (per #26), once I take some time to verify that everything works, and update the docs in a few places to match.

However, I may need to revert the cache file change. To explain a bit- They probably need a new name, but these are generated data tables, which map unicode characters to ESC/POS code pages for a given printer profile, so that print-outs and tests are fast and repeatable between systems. They are bundled to side-step the need for users to have a properly configured copy of the `iconv` extension and write access, so that there's no unnecessary restrictions on the environment we can deploy to.

Thanks a stack for the code,

**Comment by brndwgn** [comment]
Hey Mike,

Glad you're happy with the changes, and thanks for explaining the cache
files.

Let me know if you need anything else to merge!

Mike


——Mike StivalaSenior DeveloperBRND WGNfor the love of brandsBRNDWGN.COM
<http://www.brndwgn.com> | LINKEDIN
<https://www.linkedin.com/company/brnd-wgn-co-ltd?trk=fc_badge> | TWITTER
<https://twitter.com/BRNDWGN> | FACEBOOK <https://www.facebook.com/brndwgn>
T.+356 2138 3753Level 2, Corporate House
10, Oratory Street
Naxxar NXR 2504, Malta——

**Comment by silverjebs** [comment]
Hi there,
We're using your master branch in a symfony project, and it would be really nice to be able to use the namespace version. We're using it via classmap, which isn't very "nice" to use without a namespace.

Are you considering merging the pull request any time soon ? would you like some help with testing ?
cheers for now !
Paul

**Comment by mike42** [comment]
@silverjebs I've merged this in and marked it version 1.0.0. Hopefully this hits your use case. Feedback or suggestions would be appreciated on whether this could be improved further for symfony users.

For composer, it would be something like:

````
composer require mike42/escpos-php
````

And then:

````
<?php
require __DIR__ . '/vendor/autoload.php';
$printer = new Mike42\Escpos\Printer();
$printer -> text("Hello World\n");
$printer -> close();
````

**Comment by silverjebs** [comment]
Great news !
I'll give you feedback as soon as we re intgrate it (in a couple of weeks I'd imagine).

Thanks !

**Pull request merged**
