### PR TITLE
Update For Php 8 compatibitity

### PR DESCRIPTION
**Pull request by lfelizari**
Implemented sugestion from :+1: https://github.com/mike42/escpos-php/issues/1007

### CODE REVIEW

**Comment by Chris-wg** [comment]
For details on why this is needed see

https://php.watch/versions/8.0/gdimage

"From PHP 8.0 and forward, GD extension uses \GdImage class objects instead of resource s for its underlying data structures."

"Note that all functions in GD extension now returns and expects \GdImage objects instead of resource objects. Unless you explicitly call is_resource() function on return values of GD functions (such as imagecreatefromjpeg() and imagecreate()), this change will be completely trouble-free.

If you are calling is_resource, you will now need to account for the \GdImage object return type too."

**Comment by mike42** [comment]
Thanks for bringing this to my attention.  I've included this with some other changes to get the tests working on PHP 8 (see PR #1042 )

I'll release this as version 4.0 shortly.

**Comment by pajkho** [comment]
@mike42  Any update on when V4.0 will be released?

Thanks!

**Comment by mike42** [comment]
These commits have been in the `development` branch for some time, I've re-tested and released it as v4.0 just now.

- https://github.com/mike42/escpos-php/releases
- https://packagist.org/packages/mike42/escpos-php#v4.0

**Pull request closed without merging**
